# Generated by Django 5.1.7 on 2025-04-01 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('unidad', models.CharField(default='kg', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('temporada', models.CharField(choices=[('verano', 'Verano'), ('invierno', 'Invierno')], max_length=20)),
                ('tipo_comida', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena')], max_length=20)),
                ('porciones', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.insumo')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='recetas.receta')),
            ],
        ),
        migrations.CreateModel(
            name='MenuDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_comida', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena')], max_length=20)),
                ('temporada', models.CharField(choices=[('verano', 'Verano'), ('invierno', 'Invierno')], max_length=20)),
                ('comensales', models.PositiveIntegerField(default=115)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.receta')),
            ],
            options={
                'unique_together': {('fecha', 'tipo_comida', 'temporada')},
            },
        ),
    ]
