# Generated by Django 5.1.7 on 2025-04-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoInsumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('temporada', models.CharField(choices=[('verano', 'Verano'), ('invierno', 'Invierno')], max_length=20)),
                ('insumos', models.TextField()),
            ],
        ),
    ]
