# Generated by Django 5.1.7 on 2025-04-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_calculoinsumos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='unidad',
            field=models.CharField(default='unidades', max_length=20),
            preserve_default=False,
        ),
    ]
