# Generated by Django 5.2 on 2025-04-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_remove_ingrediente_unidad_calculoinsumos_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='presentacion',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
