# Generated by Django 5.2 on 2025-04-11 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_insumo_presentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='porciones',
        ),
    ]
